import { Box, Typography, Link } from "@mui/material";

function Copyright() {
  return (
    <Typography variant="body2" color="text.secondary" align="center">
      {"Copyright © "}
      <Link color="inherit" href="https://github.com/just-digital/">
        just-digital
      </Link>{" "}
      {new Date().getFullYear()}
      {"."}
    </Typography>
  );
}

export default function Footer() {
  return (
    <Box sx={{ bgcolor: "background.paper", p: 6 }} component="footer">
      <Typography
        variant="body2"
        align="center"
        color="text.secondary"
        component="p"
      >
        This site is generated by{" "}
        <Link href="https://github.com/just-digital/market-research-presenter">
          Market Research Presenter
        </Link>
      </Typography>
    </Box>
  );
}
